SConvとCausalDataBufferを実装
MLShukai/ami pull request #104
Opened 2024-03-23 11:52 UTC by myxyy

## 概要

https://github.com/MLShukai/ami/issues/103
SConvの移植とCausalDataBufferの実装までで一旦PR出します
Trainerは別で作ります

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-03-23 13:22 UTC, Geson-anko requested changes
@myxyy　実装ありがとうございます。
モデルファイルは `forward_dynamics`ディレクトリではなく、`components`直下に配置してください。`forward_dynamics`クラスを定義するファイルを`models`直下に配置するためです。
学習時とAgent上での推論時でテンソルの形状に差異が出るので、`len`や`batch`軸がない場合を判定して形状を変更する必要がありますが、それはSConvクラスではなく、Forward Dynamicsクラスの`forward` パスで実装してください。

2024-03-23 13:22 UTC, Geson-anko commented on ami/data/buffers/causal_data_buffer.py
> +            self.add(step_data)
dequeは中間要素へのアクセスが遅いので、一つずつではなくまとめて結合してください。maxlenを指定しているので古い要素は自動的に削除されます。
```suggestion
        for key in range(self.__key_list):
            self.buffer_dict[key] += new_data.buffer_dict[key]
            self.current_len = ((len(self) + len(new_data)) % self.__max_len) + 1
```

2024-03-23 16:13 UTC, myxyy commented
> @myxyy　実装ありがとうございます。 モデルファイルは `forward_dynamics`ディレクトリではなく、`components`直下に配置してください。`forward_dynamics`クラスを定義するファイルを`models`直下に配置するためです。 学習時とAgent上での推論時でテンソルの形状に差異が出るので、`len`や`batch`軸がない場合を判定して形状を変更する必要がありますが、それはSConvクラスではなく、Forward Dynamicsクラスの`forward` パスで実装してください。

https://github.com/MLShukai/ami/pull/104/commits/65adf78f4de29b0ba7579c1f6daaa8efabea3248
移動しました

2024-03-23 16:19 UTC, myxyy commented on ami/data/buffers/causal_data_buffer.py
> +            self.add(step_data)
@Geson-anko 
https://github.com/MLShukai/ami/pull/104/commits/f7de3585343f80676103d4964c91c0191a467687
修正しました
__current_lenの計算の確認をお願いします

2024-03-24 04:31 UTC, Geson-anko approved these changes
@myxyy Approveします。

2024-03-24 04:32 UTC, merged