[WIP] `VRChatOSCDiscreteActuator` を実装
MLShukai/ami pull request #127
Opened 2024-03-30 06:40 UTC by yuntan

## 概要

#98 を実装

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-03-30 08:27 UTC, yuntan commented
@Geson-anko テスト時の `SimpleUDPClient` のmock化は必要でしょうか？

2024-03-30 12:10 UTC, Geson-anko requested changes
@yuntan 実装ありがとうございます。修正よろしくお願いします。

2024-03-30 12:10 UTC, Geson-anko commented on ami/interactions/environments/actuators/vrchat_osc_discrete_actuator.py
> +from pythonosc.udp_client import SimpleUDPClient
```suggestion
```

2024-03-30 12:10 UTC, Geson-anko commented on ami/interactions/environments/actuators/vrchat_osc_discrete_actuator.py
> +        controller = InputController(SimpleUDPClient(osc_address, osc_sender_port))
こうしてください。
```suggestion
        controller = InputController((osc_address, osc_sender_port))
```

2024-03-30 12:10 UTC, Geson-anko commented on tests/interactions/environments/actuators/test_vrchat_osc_discrete_actuator.py
> +            actuator.operate(torch.tensor(ACTION_CHOICES_PER_CATEGORY))
ここのテスト意図の明示性が低いです。確かに`ACTION_CHOICES_PER_CATEGORY`を入れればエラーになりますが、ここは明らかにあり得ない値、`[-1, 999, ...]`といった値にしてください。

2024-03-30 12:43 UTC, yuntan commented
@Geson-anko 反映しました。ご確認をお願いします。

2024-03-30 13:39 UTC, Geson-anko approved these changes
Approveします。

2024-03-31 00:39 UTC, Geson-anko requested changes
@yuntan すみません、やっぱりちょっと修正あります。

2024-03-31 00:39 UTC, Geson-anko commented on tests/interactions/environments/actuators/test_vrchat_osc_discrete_actuator.py
> +    def actuator(self) -> VRChatOSCDiscreteActuator:
@yuntan すみません、やっぱりモックしてください。勝手にVRChatに値を送信されると、リセット処理がかからないなど面倒だからです。
```suggestion
    def actuator(self, mocker: MockerFixture) -> VRChatOSCDiscreteActuator:
        mocker.patch("pythonosc.SimpleUDPClient")
```

2024-03-31 02:00 UTC, yuntan commented
@Geson-anko 修正しました。

2024-03-31 04:24 UTC, Geson-anko approved these changes
@yuntan ありがとうございます。Approve します

2024-03-31 04:25 UTC, merged