TensorBoardLogger実装
MLShukai/ami pull request #147
Opened 2024-04-07 14:48 UTC by myxyy

## 概要

https://github.com/MLShukai/ami/issues/124 の実装
作業中...

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-04-07 14:49 UTC, myxyy commented
@Geson-anko 
仕様の理解が正しいか一旦確認をお願いします

2024-04-08 03:54 UTC, Geson-anko requested changes
@myxyy 試作ありがとうございます。一定**時間**経過したら記録する処理の部分はちょっと難しかったですね。とりあえずその処理の部分だけサンプルコード貼っておきます。

```py
class TensorBoardLogger:
    def __init__(self, ...):
        self.log_every_n_seconds: float = ...
        self.previous_log_time = -math.inf
        self.logged = False
    
    @property
    def current_time(self) -> float:
        return time.perf_counter()
    
    def log_available() -> bool:
        return self.current_time - self.previous_time > self.log_every_n_seconds
    
    def log(self, ...):
        if self.log_available():
            self.logged = True
            ... # tensorboard.add_scalar
        else:
            self.logged = False

    def update(self):
        if self.logged:
            self.previous_log_time = self.current_time
            self.logged = False
```

2024-04-08 03:54 UTC, Geson-anko commented on ami/tensorboard_logger.py
> +        self.previous_log_time: float | None = None
初期値は負の無限大にすると良いです。
```suggestion
        self.previous_log_time: float = -math.inf
```

2024-04-09 21:31 UTC, Geson-anko requested changes
@myxyy 実装ありがとうございます。ほぼほぼ形になってきましたね。

まず、しっかりとしたレビューや仕様策定が出来ず申し訳ありません。よくよく考えたら、Nステップごとに記録することと、N秒ごとに記録することを、一つのクラスで実行すること自体が間違いであり、それぞれ別のクラスを作る必要があると気づきました。

作るべきクラスは、次のようになります。

* 基底`TensorBoardLogger`クラス: `log_hyperparameters`などの機能が実装された抽象基底クラス。実装されるメソッドは次に示す。
   * 抽象`log_available`
   * 抽象`update`
   * 抽象`log`
   * 辞書を展開するコード
   * `log_hyperparameters`
* N秒ごとに記録する実装クラス。`log_available`の時に`log`が呼ばれた場合、`update`メソッドで`self.previous_log_time`を更新する。ログの呼び出し判定は内部フラグ`_logged: bool`で管理する方法が考えられる。
* Nステップごとに記録する実装クラス。 `update`で`self.global_step+=1`. `log_available`の判定は`global_steps % log_every_n_steps == 0`

すみません、よろしくお願いします。

2024-04-10 14:22 UTC, myxyy commented
@Geson-anko 
https://github.com/MLShukai/ami/pull/147/commits/f5e01b45e0144f3e82cd0f8c6d12fb6302076d5f
対応しました

2024-04-11 03:42 UTC, Geson-anko requested changes
@myxyy 実装ありがとうございます。

いくつかの修正ののち、マージしましょう。
* 全てのクラスを`ami/tensorboard_loggers.py`にまとめてください。これ以上新規にTensorBoardLoggerを実装することが考えられないことや、実装を追う際に一つのファイルにまとめられていた方が見やすいからです。
* 抽象基底クラスですでに`log`メソッドを実装しても良いかもしれません。`TimeIntervalLogger`だけは`log_available`の際に`log`を呼んだかどうか保存しておく必要があるので、そこだけ継承して、`super().log`の後に`self.logged = self.log_available`を呼べば良さそうです。

2024-04-11 03:42 UTC, Geson-anko commented on ami/tensorboard_logger/tensorboard_logger.py
> +        """
未実装エラー
```suggestion
    @property
    @abstractmethod
    def log_available(self) -> bool:
        """Determines whether a data can be logged.

        Returns:
            bool: whether a data can be logged.
        """
        raise NotImplementedError
```

2024-04-11 03:42 UTC, Geson-anko commented on ami/tensorboard_logger/tensorboard_logger.py
> +                if not isinstance(v, Mapping | MutableSequence):
こここういう記述できるんですね・

2024-04-11 03:42 UTC, Geson-anko commented on ami/tensorboard_logger/time_interval_logger.py
> +            self.tensorboard.add_scalar(tag, scalar, self.global_step)
`typing_extensions.override`デコレータを使って、オーバーライドメソッドであることを明示してください。
```suggestion

    @override
    @property
    def log_available(self) -> bool:
        return time.perf_counter() - self.previous_log_time > self.log_every_n_seconds

    @override
    def update(self) -> None:
        self.global_step += 1
        self.previous_log_time = time.perf_counter()

    @override
    def log(self, tag: str, scalar: Tensor | float | int) -> None:
        if self.log_available:
            self.tensorboard.add_scalar(tag, scalar, self.global_step)
```

2024-04-11 03:42 UTC, Geson-anko commented on ami/tensorboard_logger/step_interval_logger.py
> +            self.tensorboard.add_scalar(tag, scalar, self.global_step)
`typing_extensions.override`デコレータを使って、オーバーライドメソッドであることを明示してください。

2024-04-11 05:26 UTC, Geson-anko commented on ami/tensorboard_logger/tensorboard_logger.py
> +        return {k: v for d in ld for k, v in d.items()}
このメソッドは、`dict(collections.ChainMap(*list_of_dict))`とほぼ等価です

2024-04-12 12:46 UTC, myxyy commented on ami/tensorboard_logger/step_interval_logger.py
> +            self.tensorboard.add_scalar(tag, scalar, self.global_step)
https://github.com/MLShukai/ami/pull/147/commits/c39078e66b65e9537ac23b0ecc4d88e105dcfec7 対応しました

2024-04-12 12:46 UTC, myxyy commented on ami/tensorboard_logger/time_interval_logger.py
> +            self.tensorboard.add_scalar(tag, scalar, self.global_step)
https://github.com/MLShukai/ami/pull/147/commits/c39078e66b65e9537ac23b0ecc4d88e105dcfec7 対応しました

2024-04-12 12:46 UTC, myxyy commented on ami/tensorboard_logger/tensorboard_logger.py
> +        """
https://github.com/MLShukai/ami/pull/147/commits/c31fe55f1676195003ba53970eeb922af0898132 修正しました

2024-04-12 12:46 UTC, myxyy commented on ami/tensorboard_logger/time_interval_logger.py
> +            self.tensorboard.add_scalar(tag, scalar, self.global_step)
https://github.com/MLShukai/ami/pull/147/commits/1f59fc0501033a5b8bf1c3648e449dcdf633b92c 修正しました

2024-04-12 12:54 UTC, myxyy commented on ami/tensorboard_logger/tensorboard_logger.py
> +        return {k: v for d in ld for k, v in d.items()}
https://github.com/MLShukai/ami/pull/147/commits/210688a4c59d08e55cf88ecbcd0b115c85566467 対応しました

2024-04-12 12:55 UTC, myxyy commented
> @myxyy 実装ありがとうございます。
> 
> いくつかの修正ののち、マージしましょう。
> 
> * 全てのクラスを`ami/tensorboard_loggers.py`にまとめてください。これ以上新規にTensorBoardLoggerを実装することが考えられないことや、実装を追う際に一つのファイルにまとめられていた方が見やすいからです。
> * 抽象基底クラスですでに`log`メソッドを実装しても良いかもしれません。`TimeIntervalLogger`だけは`log_available`の際に`log`を呼んだかどうか保存しておく必要があるので、そこだけ継承して、`super().log`の後に`self.logged = self.log_available`を呼べば良さそうです。

https://github.com/MLShukai/ami/pull/147/commits/11ff83dc4b158251452a9fa116a56c599f26b349
https://github.com/MLShukai/ami/pull/147/commits/c89a3850129047eaa03583ab50e2ed3b63233fa5
対応しました

2024-04-12 13:54 UTC, Geson-anko approved these changes
@myxyy モジュールファイルの位置とファイル名を修正しておきました。Approveします。

2024-04-12 14:15 UTC, merged