`pause`と`resume`のイベントコールバックの呼び出し処理を実装
MLShukai/ami pull request #155
Opened 2024-04-14 12:30 UTC by Geson-anko

## 概要

#130 ThreadCommandHandlerにコールバックを登録し、**pause/resumeされるスレッド上で同期的に呼び出される**ように実装しました。すなわち、そのスレッドクラスの`on_paused`, `on_resumed`はスレッドセーフであり、スレッドが動作中に割り込むことはありません。よって、Systemが`pause`し、すぐに`resume`した場合などは、イベント関数が呼び出されない場合があります。

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-04-15 21:51 UTC, Geson-anko commented
@yuntan コールバックの呼び出し順の制御や重複などが面倒になるので単一のコールバックのみを指定できるようにリファクタリングしました。https://github.com/MLShukai/ami/pull/155/commits/5ad9d51c63a98d66ca9de1f4ec6a9aa80baff646

2024-04-18 23:41 UTC, yuntan requested changes
まだ途中までしか見られていませんが、一旦お送りします。

2024-04-18 23:41 UTC, yuntan commented on ami/threads/thread_control.py
> +    on_resumed: OnResumedCallbackType = dummy_on_resumed
これでも良いと思います。

```python
    on_paused: OnPausedCallbackType = lambda: None
    on_resumed: OnResumedCallbackType = lambda: None
```

2024-04-18 23:41 UTC, yuntan commented on ami/threads/thread_control.py
`ThreadCommandHandler.is_active()` の意味がよく分かりません。シャットダウン状態を反転させたものがアクティブ状態であるというのがよく分からないです。アクティブでありかつpausedであるというのが更にややこしいです。素直に `is_shutdown()` をフラグにしても良いのではないでしょうか？

2024-04-18 23:41 UTC, yuntan commented on ami/threads/thread_control.py
> +
`self.stop_if_paused()  # blocking` などコメントをお願いします。

2024-04-18 23:41 UTC, yuntan commented on ami/threads/thread_control.py
> +        if paused:
`# resuming system` などコメントをお願いします。

2024-04-19 03:14 UTC, Geson-anko commented on ami/threads/thread_control.py
> +    on_resumed: OnResumedCallbackType = dummy_on_resumed
@yuntan `lambda`式は型アノテーションができないのでmypyが許してくれません。実際引数の名称指定やオプションの指定などができないのでこういったシステムを記述する際にあまり好ましくないです。

2024-04-19 03:23 UTC, Geson-anko commented on ami/threads/thread_control.py
@yuntan そこがややこしいのは申し訳ないのですが、今回のPRの内容と関係ないのでパスします。

そのメソッドを作った意図ですが、例えば`while`ループで`not`をつける処理を忘れたくないという意図があります。また、システムにおける`shutdown`の対義語が`active`なので、そういった名称にしています。最初の検討で`system.is_shutdown/is_active`という用法を考えていたので、`handler`になった今は`is_system_active`とかいう名称にすべきだったんですかね。

あと一応の見解ですが、システムが`pause`していたとしても、`resume`する応答を受け付けられます。よって、`pause`していたとしても、システム自体は`active`である、と考えます。

2024-04-19 03:25 UTC, Geson-anko commented on ami/threads/thread_control.py
> +
メソッドの名称から予想できるのではないでしょうか。今回のPRとは関係がないので、別のPRで対応しましょう。

2024-04-19 03:30 UTC, Geson-anko commented on ami/threads/thread_control.py
> +        if paused:
修正しました。
https://github.com/MLShukai/ami/pull/155/commits/330025ef852d7d1b028b02f49b57bbdcd79d8779

2024-04-19 03:31 UTC, Geson-anko commented on ami/threads/thread_control.py
> +
これ、`manage_loop`メソッドのわかりやすさのことを話していたんですね。修正しました。https://github.com/MLShukai/ami/pull/155/commits/330025ef852d7d1b028b02f49b57bbdcd79d8779

2024-04-19 03:49 UTC, yuntan approved these changes

2024-04-19 04:21 UTC, merged