ImageVAETrainerにlogger追加
MLShukai/ami pull request #158
Opened 2024-04-16 12:24 UTC by myxyy

## 概要

Trainerのlogger実装の方針の確認です

* updateタイミングは適切か
* ログフォルダ名は適切か

あたりが気になっています

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-04-17 02:26 UTC, Geson-anko requested changes
@myxyy 実装ありがとうございます。loggerの`update`メソッドはステップごとに呼んでください。もし`update`というメソッド名が不適切だと思う場合は、`step`など、適切なものに置き換えてしまって構いません。

あと`tensorboard`の`global_step`も状態なので、それを`save_state`/`load_state`できるようにしておく必要があるかもしれません。

2024-04-17 02:26 UTC, Geson-anko commented on configs/trainers/image_vae.yaml
> +    log_dir: ${paths.log_dir}/tensorboard
`ami/configs/paths/default.yaml`に`tensorboard_dir: ${paths.log_dir}/tensorboard`を追加してください。そして以下のようにすると良いと思います。Trainerごとに個別のTensorBoardディレクトリを用意する理由は、再開した際にその個別フォルダに新規のログファイルが生成され、引継が行われるというTensorBoardの仕様のためです。

```suggestion
    log_dir: ${paths.tensorboard_dir}/image_vae_trainer
```

2024-04-17 02:26 UTC, Geson-anko commented on ami/trainers/image_vae_trainer.py
> +                self.logger.log("image_vae_loss", loss)
このようにすると、`image_vae`というタブの中に`loss`がまとめられて見やすくなると思います。
```suggestion
                self.logger.log("image_vae/loss", loss)
```

2024-04-17 22:48 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +        self.logger.update()
https://github.com/MLShukai/ami/pull/158/commits/53e29e7f6c301c8997e92807f089f0ad0a62f148
epochのループ内ではなくbatchのループ内でよいでしょうか？修正しました

2024-04-17 22:54 UTC, myxyy commented on configs/trainers/image_vae.yaml
> +    log_dir: ${paths.log_dir}/tensorboard
https://github.com/MLShukai/ami/pull/158/commits/da4036c8674ea4183902e5d9503779873220a489
修正しました

2024-04-17 22:55 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +                self.logger.log("image_vae_loss", loss)
https://github.com/MLShukai/ami/pull/158/commits/f8c22ce7210ac142cc6a715c08b8710e7e9f63c4
修正しました

2024-04-18 00:09 UTC, myxyy commented
https://github.com/MLShukai/ami/pull/158/commits/5b72324fd8f717191ee1a6e7620085d8aa4d7ab1
loggerのglobal_stepを保存するようにしました

2024-04-18 22:55 UTC, Geson-anko commented
@myxyy テストが通らない原因なのですが、GitHubのテスト実行はどうやらマージ後のリポジトリの状態を再現して実行するらしく、mainブランチへのマージ後、 `configs/trainers/image_vae_forward_dynamics_ppo.yaml`にTensorboardLoggerが追加されていないためにエラーが出てしまったようです。

2024-04-18 22:58 UTC, Geson-anko commented
それぞれのTrainerのベースの設定ファイルが共有されないと困るので、ちょっとそこ修正します。

2024-04-18 22:58 UTC, Geson-anko requested changes
@myxyy 修正ありがとうございます。logの出力ディレクトリだけ修正した後にマージしましょう。

2024-04-18 22:58 UTC, Geson-anko commented on ami/trainers/image_vae_trainer.py
> +        self.logger.update()
@myxyy `logger.update()`は`optimizer.step()`に対応するものだと考えてください。

2024-04-18 23:39 UTC, Geson-anko approved these changes
手隙だったので`output_dir`への修正も行いました。https://github.com/MLShukai/ami/pull/158/commits/054974e34bae8fb3765cd6de7b9ac167426c2977

ただ、メイン実行したランタイムでしか`hydra:runtime.output_dir`が使えないようで、テストでそこが詰まるので修正しました。

2024-04-19 13:09 UTC, merged