Feature/#165/add logger forwarddynamicstrainer ppopolicytrainer
MLShukai/ami pull request #166
Opened 2024-04-19 16:06 UTC by myxyy

## 概要

https://github.com/MLShukai/ami/issues/165
https://github.com/MLShukai/ami/pull/164 がマージされてからマージします

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-04-19 23:43 UTC, Geson-anko requested changes
@myxyy 実装ありがとうございます。loggerの状態の持ち方と、PPOPolicyTrainerのlog方法についていくつか修正お願いします。

2024-04-19 23:43 UTC, Geson-anko commented on ami/trainers/forward_dynamics_trainer.py
> +        self.logger_state = self.logger.state_dict()
46, 74, 112, 117行目に関わるものなのですが、別にloggerの状態は推論スレッドと学習スレッドで入れ替わらないので、`train`を実行するごとに属性に保存しなくても良いはずです。
optimizerの場合は内部パラメータの入れ替えが`train`を実行するごとに発生するのでこういった記述が必要です。そこと記述方式を合わせるという意図であれば今回の書き方でOKです。

```suggestion
```

2024-04-19 23:43 UTC, Geson-anko commented on ami/trainers/forward_dynamics_trainer.py
> +        self.logger.load_state_dict(self.logger_state)
先のコメントを参照
```suggestion
```

2024-04-19 23:43 UTC, Geson-anko commented on ami/trainers/forward_dynamics_trainer.py
> +        torch.save(self.logger_state, path / "logger.pt")
先のコメントを参照
```suggestion
        torch.save(self.logger.state_dict(), path / "logger.pt")
```

2024-04-19 23:43 UTC, Geson-anko commented on ami/trainers/forward_dynamics_trainer.py
> +        self.logger_state = torch.load(path / "logger.pt")
先のコメントを参照
```suggestion
        self.logger.load_state_dict(torch.load(path / "logger.pt"))
```

2024-04-19 23:43 UTC, Geson-anko commented on ami/trainers/ppo_policy_trainer.py
> +                self.logger.log("ppo_policy/clipfrac", out["clipfrac"])
`for`文使いましょう。

```suggestion
                self.logger.log("ppo_policy/loss", out["loss"])
                for name, value in out.items():
                    self.logger.log(f"ppo_policy/{name}", value)
```

2024-04-19 23:45 UTC, myxyy commented on ami/trainers/ppo_policy_trainer.py
> +                self.logger.log("ppo_policy/clipfrac", out["clipfrac"])
entropyについてはどうしましょうか、そのままだとlogが取れなかったので

2024-04-19 23:46 UTC, Geson-anko commented on ami/trainers/ppo_policy_trainer.py
> +                self.logger.log("ppo_policy/clipfrac", out["clipfrac"])
@myxyy PPOPolicyTrainerの`training_step`のoutputになぜか`mean`されてない生の`entropy`を入れてしまっていますが、本来は`entropy_loss`を返すものなのでそこの修正もお願いします。すみません。

2024-04-20 00:35 UTC, myxyy commented on ami/trainers/ppo_policy_trainer.py
> +                self.logger.log("ppo_policy/clipfrac", out["clipfrac"])
https://github.com/MLShukai/ami/pull/166/commits/7d18874f72d19569d6431b40ad6bafb0bde042e0
修正しました
`StepOutput`のforはmypy通らなかったので`StepOutput`から`dict[str, Tensor]`にしました

2024-04-20 00:35 UTC, myxyy commented on ami/trainers/forward_dynamics_trainer.py
> +        self.logger_state = torch.load(path / "logger.pt")
https://github.com/MLShukai/ami/pull/166/commits/d839a30aa88951cdf23d99f7259c854b5ed98541
修正しました

2024-04-20 00:35 UTC, myxyy commented on ami/trainers/forward_dynamics_trainer.py
> +        torch.save(self.logger_state, path / "logger.pt")
https://github.com/MLShukai/ami/pull/166/commits/d839a30aa88951cdf23d99f7259c854b5ed98541
修正しました

2024-04-20 00:35 UTC, myxyy commented on ami/trainers/forward_dynamics_trainer.py
> +        self.logger.load_state_dict(self.logger_state)
https://github.com/MLShukai/ami/pull/166/commits/d839a30aa88951cdf23d99f7259c854b5ed98541
修正しました

2024-04-20 00:36 UTC, myxyy commented on ami/trainers/forward_dynamics_trainer.py
> +        self.logger_state = self.logger.state_dict()
https://github.com/MLShukai/ami/pull/166/commits/d839a30aa88951cdf23d99f7259c854b5ed98541
修正しました

2024-04-20 00:48 UTC, Geson-anko commented on ami/trainers/ppo_policy_trainer.py
> +                self.logger.log("ppo_policy/clipfrac", out["clipfrac"])
@myxyy マジっすか。そこ通りませんでしたか。了解です。

2024-04-20 01:09 UTC, Geson-anko commented
@myxyy loggerのload_state_dictが意図した通り呼ばれているかテストの修正しておきました。あとは実際に動かして動作確認したらApproveしますね。https://github.com/MLShukai/ami/pull/166/commits/cc4b420c844656247202db98c0e67e870f8cc130

2024-04-20 07:34 UTC, myxyy commented
@Geson-anko 
動かしたTensorboardのスクショ貼りました

2024-04-20 08:46 UTC, Geson-anko approved these changes
@myxyy 忘れてましたが CuriosityImagePPOAgentに`TimeIntervalLogger`を入れてませんね... 今回は Trainerだけの実装とするので、Approveします。

2024-04-20 09:28 UTC, merged