Thread制御をリファクタリング
MLShukai/ami pull request #185
Opened 2024-04-30 07:49 UTC by Geson-anko

## 概要

#181 

まずは #184 をマージしてください。

## 変更内容

* `ThreadControllerStatus`という、ThreadControllerの状態の読み取り専用オブジェクトを作成しました。
* `WebApiHandler`にThreadControllerの状態のみを参照可能にし、命令を`ThreadSafeFlag`で受け渡すようにしました
* `WebApiHandler`は常にバックグラウンドデーモンスレッドで実装されるため、その処理を`WebApiHandler.run_in_background`としました。
* `MainThread`クラスの`worker`ループでWebApiHandlerの命令を元にスレッド制御処理を行うよう修正しました。
* これらの変更に伴ってテストを修正しました。

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-05-01 23:01 UTC, yuntan requested changes

2024-05-01 23:08 UTC, yuntan commented on ami/threads/thread_control.py
> +        self.is_resumed = controller.is_resumed
`is_shutdown` をプロパティメソッドとしないと値が更新されないのではないでしょうか？

2024-05-01 23:12 UTC, yuntan commented on ami/threads/thread_control.py
> +        self.is_resumed = controller.is_resumed
変数ではなく、メソッドを渡しているのですね。失礼しました。

2024-05-02 03:49 UTC, Geson-anko commented on ami/threads/main_thread.py
> +                time.sleep(0.001)
その通りです。仕事終わったら修正します

2024-05-02 03:51 UTC, Geson-anko commented on ami/threads/web_api_handler.py
> +        return {"result": "ok"}
これはゆんたんさんが書いたコードなので、そのようにしていますが、`console.py`の方でresultを参照してしまっているのでこのまま残して置いて欲しいです。

2024-05-02 09:08 UTC, yuntan commented on ami/threads/web_api_handler.py
> +        return {"result": "ok"}
そうですね、元々私が書いたコードも成功時とエラー時の一貫性がないですね…

とりあえずこのままということで。

2024-05-02 11:21 UTC, Geson-anko commented on ami/threads/main_thread.py
> +                time.sleep(0.001)
@yuntan 修正しました。https://github.com/MLShukai/ami/pull/185/commits/68d2c9c90553b462d27262550064547e42d9651f

2024-05-02 11:21 UTC, Geson-anko commented on ami/threads/web_api_handler.py
> +        self._pause_flag.set()
@yuntan 修正しました。https://github.com/MLShukai/ami/pull/185/commits/68d2c9c90553b462d27262550064547e42d9651f

2024-05-03 05:24 UTC, yuntan requested changes

2024-05-03 05:24 UTC, yuntan commented on ami/threads/main_thread.py
> +
```py
try:
    self.blocking_while_processing_received_commands()
```

2024-05-03 05:24 UTC, yuntan commented on ami/threads/main_thread.py
> +                    self.thread_controller.shutdown()
```py
case ControlCommands.SHUTDOWN:
    self.logger.info("Shutting down...")
    self.thread_controller.shutdown()
    break
```

2024-05-03 05:24 UTC, yuntan commented on ami/threads/main_thread.py
> +    def process_received_commands(self) -> None:
```py
def blocking_while_processing_received_commands(self)
```

2024-05-03 05:24 UTC, yuntan commented on ami/threads/web_api_handler.py
> +        return self._received_commands_queue.get_nowait()
```py
return self._received_commands_queue.get()
```

2024-05-03 05:24 UTC, yuntan commented on ami/threads/web_api_handler.py
> +    def receive_command(self) -> ControlCommands:
```py
def blocking_until_receive_command(self):
```

2024-05-03 06:15 UTC, merged

2024-05-03 06:35 UTC, Geson-anko commented
@yuntan レビューありがとうございますが、今回のレビュー内容はコードのdocstringやテストから読み取れる意図から乖離しています。

blockingもしませんし、whileループは有限です。queueにある全てのメッセージを処理する際に`for`が使えないためこの記述になっています。`get_nowait`は空のqueueに対して使うとエラーを起こす事が好ましいためこの記述です。これはテスト内容から判別できるでしょう。

もしお疲れのようでしたら、ゆっくり休んでください。