Hifi-GANのDiscriminatorを追加
MLShukai/ami pull request #242
Opened 2024-12-08 10:22 UTC by zassou65535

## 概要

Hifi-GANの学習で必要となるDiscriminatorを追加

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-12-10 06:40 UTC, Geson-anko requested changes
@zassou65535 Don't Repeat Yourself.
繰り返しの少ない簡潔なコードを書くことが基本です。どうしてもロジックが汚くなってしまう場合や、大規模な回収が必要になる場合以外はDRYを意識してください。

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
@zassou65535 
これは次のPRで行ってほしいことです。
hifigan_generatorとセットで定義されると思うので、`models/hifigan/...`の中にgenerator.pyとdiscriminators.pyを実装してください。

`get_padding`はgeneratorとdiscriminatorで共通なので、utils.pyに記述してそこから相対参照するようにしてください。

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        )
ここはConv1dで実装できる内容であること、またfor文を使って実装することが簡潔かつ健全です。
またマジックナンバーが多すぎます。ちゃんと変数にまとめ、説明的にしてください。
DRY (Don't Repeat Yourself)の原則に従い、繰り返し似た内容のコードを書くことは基本避けましょう。（正し、それによって大規模な修正が必要になる場合はこの限りではありません。将来的な修正項目にはなりますが）
```suggestion
        channels = [
            (in_channels, 32),
            (32, 128),
            (128, 512),
            (512, 1024),
            (1024, 1024)
        ]
        self.convs = nn.ModuleList()
        for i, (in_ch, out_ch) in enumerate(channels, start=1):
            padding = get_padding(kernel_size, 1)
            if i == len(channels):
                padding = 2
            self.convs.append(
                weight_norm(nn.Conv1d(in_ch, out_ch, kernel_size, stride, padding)
            )
```

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        x = x.view(batch_size, channels, sample_size // self.period, self.period)
Conv1dを使用することに関連して、`period`の軸をmove_dim, flattenして、`(batch_size * self.period, channels, sample_size // self.period)`としてconvに通しましょう。
その後に、逆の操作をして元に形状と軸を元に戻しましょう

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        )
for文で書く

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        return y_d_rs, y_d_fs, fmaps_rs, fmaps_fs
realとfakeに全く同じ操作を適用するため、引数は`waveforms`一つだけでよく、forwardの外側の関数でそれぞれreal_waveformsとfake_waveformsを通す、という実装にするべきです。

```py
y_d_rs, fmaps_rs = forward(real_waveforms)
y_d_fs, fmaps_fs = forward(fake_waveforms)
```

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +class DiscriminatorP(nn.Module):
`P`の意図が不明です。
```suggestion
class DiscriminatorPeriod(nn.Module):
```

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +class DiscriminatorS(nn.Module):
`S`の意図が不明です。
```suggestion
class DiscriminatorScale(nn.Module):
```

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        )
for文を使う。

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        )
この程度であればfor文で記述しなくても問題ありません。3回の繰り返しが限度です。

2024-12-10 06:40 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        return y_d_rs, y_d_fs, fmaps_rs, fmaps_fs
ここも先のコメントと同じように、二重に処理が書かれているためこのforwardメソッドの外側で2回このforwardを実行するべきです。

2024-12-12 11:52 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +class DiscriminatorP(nn.Module):
https://github.com/MLShukai/ami/pull/242/commits/284b7a157cb7e71a8c47ba11c4a401c81c0a90e6 で修正
(`DiscriminatorPeriod`だと"Discriminatorの周期"になってしまうのが気になったから`PeriodDiscriminator`としてある)

2024-12-12 11:53 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +class DiscriminatorS(nn.Module):
https://github.com/MLShukai/ami/pull/242/commits/284b7a157cb7e71a8c47ba11c4a401c81c0a90e6 で修正
(`DiscriminatorScale`だと"Discriminatorの規模"になってしまうのが気になったから`ScaleDiscriminator`としてある)

2024-12-12 12:04 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        )
https://github.com/MLShukai/ami-vconf24/commit/4be5389e4b19a1afc5721289f1e19c236590aa79 で修正

2024-12-12 12:21 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        )
[`DiscriminatorP`でのこれ](https://github.com/MLShukai/ami/pull/242#discussion_r1877424438) みたいな、例えば引数が`period`だけ違っててほか全部同じみたいな事例ならfor文の方が見通しよく書けそうっていうのは分かる
けど、今回の場合ってそれぞれ引数が微妙に違ったりしてて、そのせいでもしfor文で書こうとすると下みたいになる
でもこれだったら元の方が見やすくない？どう？
```python
conv1d_args = (
    {"in_channels": in_channels, "out_channels": 128, "kernel_size": 15, "stride"=1, "groups": 1, "padding": 7},
    {"in_channels": 128, "out_channels": 128, "kernel_size": 41, "stride"=2, "groups": 4, "padding": 20},
    {"in_channels": 128, "out_channels": 256, "kernel_size": 41, "stride"=2, "groups": 16, "padding": 20},
    {"in_channels": 256, "out_channels": 512, "kernel_size": 41, "stride"=4, "groups": 16, "padding": 20},
    {"in_channels": 512, "out_channels": 1024, "kernel_size": 41, "stride"=4, "groups": 16, "padding": 20},
    {"in_channels": 1024, "out_channels": 1024, "kernel_size": 41, "stride"=1, "groups": 16, "padding": 20},
    {"in_channels": 1024, "out_channels": 1024, "kernel_size": 5, "stride"=1, "groups": 1, "padding": 2},
)
self.convs = nn.ModuleList(
    [
        norm_f(
            nn.Conv1d(
                arg["in_channels"], 
                arg["out_channels"], 
                arg["kernel_size"], 
                arg["stride"], 
                groups=arg["groups"], 
                padding=arg["padding"]
            ) for arg in conv1d_args
        )
    ]
)
```

2024-12-12 12:52 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        return y_d_rs, y_d_fs, fmaps_rs, fmaps_fs
https://github.com/MLShukai/ami/pull/242/commits/6c051d01f440915cb477897b713c12c9390a6a9e で修正

2024-12-12 12:52 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        return y_d_rs, y_d_fs, fmaps_rs, fmaps_fs
https://github.com/MLShukai/ami/pull/242/commits/6c051d01f440915cb477897b713c12c9390a6a9e で修正

2024-12-15 23:48 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        )
@zassou65535 う、なるほど、、、これは面倒くさいね。
仕方がないのでforでなく展開して書こうか...

2024-12-25 10:07 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        x = x.view(batch_size, channels, sample_size // self.period, self.period)
https://github.com/MLShukai/ami/pull/242/commits/461767c4bcbdea7e7ea028daa3aca932b5c213b9 で修正

2024-12-25 10:15 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        x = x.view(batch_size, channels, sample_size // self.period, self.period)
[これに関係したcommit](https://github.com/MLShukai/ami/commit/461767c4bcbdea7e7ea028daa3aca932b5c213b9)これについて一応自分でもチェックはしてるんだけど、念のため次元の変形周りで間違った変形とかしてないか重点的に確認してもらえると助かる

2024-12-25 10:20 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        )
https://github.com/MLShukai/ami/pull/242/commits/461767c4bcbdea7e7ea028daa3aca932b5c213b9 で修正

2024-12-26 06:26 UTC, Geson-anko approved these changes
@zassou65535 本当に綺麗な実装になったと思う。素晴らしい。reshape周りでコメントありますが、Approveします。

2024-12-26 06:26 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        x = x.contiguous().view(batch_size * self.period, channels, sample_size // self.period)
ここ`reshape`使うと便利かも
```suggestion
        x = x.reshape(batch_size * self.period, channels, sample_size // self.period)
```

2024-12-26 06:26 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +            fmap = x.contiguous().view(self.period, batch_size, x.size(-2), x.size(-1))
ここは`contiguous`いらないと思う。心配なら`view`じゃなく`reshape`にするとか
```suggestion
            fmap = x.view(self.period, batch_size, x.size(-2), x.size(-1))
```

2024-12-26 06:26 UTC, Geson-anko commented on ami/models/hifigan_discriminators.py
> +        x = x.contiguous().view(self.period, batch_size, x.size(-2), x.size(-1))
ここも
```suggestion
        x = x.view(self.period, batch_size, x.size(-2), x.size(-1))
```

2024-12-26 08:35 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        x = x.contiguous().view(batch_size * self.period, channels, sample_size // self.period)
https://github.com/MLShukai/ami/pull/242/commits/676f67d9bcbaac4b812415342fee7106a0dd924f で修正

2024-12-26 08:36 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +            fmap = x.contiguous().view(self.period, batch_size, x.size(-2), x.size(-1))
https://github.com/MLShukai/ami/pull/242/commits/676f67d9bcbaac4b812415342fee7106a0dd924f で修正

2024-12-26 08:36 UTC, zassou65535 commented on ami/models/hifigan_discriminators.py
> +        x = x.contiguous().view(self.period, batch_size, x.size(-2), x.size(-1))
https://github.com/MLShukai/ami/pull/242/commits/676f67d9bcbaac4b812415342fee7106a0dd924f で修正

2024-12-26 08:39 UTC, merged