ロギングの設定ファイルを仮実装
MLShukai/ami pull request #35
Opened 2024-02-04 05:03 UTC by yuntan

## 概要
#29 を仮実装。

## 変更内容
- 追加：YAMLファイル
- 追加：loggerモジュール

## 影響範囲
特になし。

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

#29 を参照。

2024-02-04 08:18 UTC, Geson-anko requested changes
@yuntan 実装ありがとうございます。正常に動作することをこちらでも確認したいので、`samples/logging_demo.py`を作成して、そこにログ設定の初期化や各スレッドのロガーでのログ処理の実行を行なう処理を記述してください。

2024-02-04 08:18 UTC, Geson-anko commented on ami/logger.py
> +    return __get_thread_logger("trainer", name)
学習スレッドの名前は`training`で統一します。
```suggestion
def get_training_thread_logger(name: str) -> logging.Logger:
    return __get_thread_logger("training", name)
```

2024-02-04 08:18 UTC, Geson-anko commented on ami/logger.py
> +        return logging.getLogger(thread_name)
この処理が必要な理由説明してもらえますか？

2024-02-04 08:18 UTC, Geson-anko commented on ami/logger.py
> +logging.captureWarnings(True)
`samples/logging_demo.py`にデモコードを追加して、そちらに初期化処理の記述をサンプルとして置いてくれませんか？ 
ロガーの初期化処理も実は `hydra`に任せようと思ってるので、pythonコードとしては `logger`の取得コードだけで十分です。

2024-02-04 08:18 UTC, Geson-anko commented on samples/logging.yaml
> +    handlers: [inferenceFile]
命名はsnakeケースで統一をお願いします(pythonなので)
`rootConsole` -> root_console` のように変更お願いします。

2024-02-04 08:18 UTC, Geson-anko commented on samples/logging.yaml
> +  trainerFile:
`training`でお願いします。t
```suggestion
  training_file:
```

2024-02-04 08:18 UTC, Geson-anko commented on samples/logging.yaml
> +    filename: logs/inference/log.txt
ログファイル名は<filename>.logとしてください。
```suggestion
    filename: logs/root.log
    when: D
    level: DEBUG
    formatter: simple

  mainFile:
    class: logging.handlers.TimeRotatingFileHandler
    filename: logs/main.log
    when: D
    level: DEBUG
    formatter: simple

  trainerFile:
    class: logging.handlers.TimeRotatingFileHandler
    filename: logs/training.log
    when: D
    level: DEBUG
    formatter: simple

  inferenceFile:
    class: logging.handlers.TimeRotatingFileHandler
    filename: logs/inference.log
```

2024-02-04 13:17 UTC, yuntan commented on ami/logger.py
> +        return logging.getLogger(thread_name)
不要なので、削除します。

2024-02-04 13:48 UTC, yuntan commented on ami/logger.py
> +        return logging.getLogger(thread_name)
このコード、多分別の処理を書こうとしたらGitHub Copilotが提案してきたものをそのままsubmitしたパターンですね…

コミット前にコードを確認してなかったのがまずかったですね。

2024-02-04 14:56 UTC, yuntan commented on ami/logger.py
> +    return __get_thread_logger("trainer", name)
推論スレッドは `InferenceThread` ですか？ `InteractionThread` ですか？

2024-02-04 15:38 UTC, yuntan commented
現状以下のエラーで動かないです。

```
ModuleNotFoundError: No module named 'logging.handlers.TimeRotatingFileHandler'; 'logging.handlers' is not a package
```

2024-02-05 01:46 UTC, yuntan commented
> 現状以下のエラーで動かないです。
> 
> ```
> ModuleNotFoundError: No module named 'logging.handlers.TimeRotatingFileHandler'; 'logging.handlers' is not a package
> ```

修正しました。今の出力は以下になります。

```sh
> poetry run python samples/logging_demo.py
2024-02-05 10:06:36,743 DEBU main.very_very_l | This is a debug message
2024-02-05 10:06:36,743 INFO training.very_ve | This is an info message
2024-02-05 10:06:36,743 WARN inference.very_v | This is a warning message
Module name is empty
Invalid module name: ".demo"
Invalid module name: "demo."
Invalid module name: "try..demo"
```

2024-02-06 08:22 UTC, Geson-anko commented
@yuntan 修正のプッシュありがとうございました．私の方でもいくつか修正しました．
1. import文は基本的にファイルの先頭で書くようにします．https://github.com/MLShukai/ami/pull/35/commits/2718131a8efb2aaf3d4d6add977ca2fc462498c3
2. 実機能のテストは `pytest`のフレームワークを用いてテストします．https://github.com/MLShukai/ami/pull/35/commits/2718131a8efb2aaf3d4d6add977ca2fc462498c3
3. `logging_demo.py`の出力先を変更しました．https://github.com/MLShukai/ami/pull/35/commits/0b3dc759aad5201679a48f9a34c5e10c84e7c330

2024-02-06 08:24 UTC, Geson-anko approved these changes

2024-02-06 09:42 UTC, yuntan commented
@Geson-anko ありがとうございます。確認しました。

マージはマージコミットを作成する形で行えばいいですか？

2024-02-06 10:15 UTC, Geson-anko commented
@yuntan Github上からマージしてください。

2024-02-06 10:16 UTC, merged

2024-02-06 10:19 UTC, yuntan commented
@Geson-anko GitHub上でマージする方法が3種類あるので、そのどれを使えばいいか一応確認でお送りしました。デフォルトはマージコミットです。

2024-02-07 03:54 UTC, Geson-anko commented
@yuntan え，マージする方法3つもあるんですか？デフォルトのものでお願いします．