メインスレッドにWeb APIを仮実装
MLShukai/ami pull request #39
Opened 2024-02-09 04:54 UTC by yuntan

## 概要

#26 の実装。

## 変更内容

- `MainThread` クラスを仮実装
- `WebApiHandler` クラスを仮実装
- Web APIをbottleで実装

## 影響範囲

特になし。

## Submit前の確認項目

- [X] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [X] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [X] この PR で導入されたすべての変更点をリストアップしましたか?
- [X] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

`poetry run python samples/web_api_demo.py` でメインスレッドを起動し、別のターミナルで `curl` コマンドを実行することでテストできます。

```sh
> curl http://localhost:8080/api/status
{"status": "active"}⏎                                                                                            
> curl -I http://localhost:8080/api/status
HTTP/1.0 200 OK
Date: Thu, 08 Feb 2024 09:40:52 GMT
Server: WSGIServer/0.2 CPython/3.11.7
Content-Type: application/json
Content-Length: 20
> curl http://localhost:8080/api/shutdown
{"error": "Invalid API method"}⏎                      
> curl -I http://localhost:8080/api/shutdown
HTTP/1.0 405 Method Not Allowed
Date: Thu, 08 Feb 2024 09:38:22 GMT
Server: WSGIServer/0.2 CPython/3.11.7
Allow: POST
Content-Type: application/json
Content-Length: 31
> curl -X POST http://localhost:8080/api/shutdown
{"result": "ok", "status": "stopped"}⏎                                                                           
```

2024-02-09 04:56 UTC, yuntan commented
ローカルで `make run` すると一部のテストが失敗します。

```
tests/interactions/test_interval_adustors.py::TestSleepIntervalAdjustor::test_adjust[0.01-50] FAILED      [ 45%]
tests/interactions/test_interval_adustors.py::TestSleepIntervalAdjustor::test_adjust[0.05-10] FAILED      [ 47%]
```

2024-02-09 10:26 UTC, Geson-anko commented
> ローカルで `make run` すると一部のテストが失敗します。
> 
> ```
> tests/interactions/test_interval_adustors.py::TestSleepIntervalAdjustor::test_adjust[0.01-50] FAILED      [ 45%]
> tests/interactions/test_interval_adustors.py::TestSleepIntervalAdjustor::test_adjust[0.05-10] FAILED      [ 47%]
> ```

おそらく MacOSでテストしていますね？ `time.sleep`は nanosleepを実装しているOS上じゃないと精度が出ないので，テストが落ちると思います．MacOSの`time.sleep`はWindowsよりは良いですが，可能ならLinuxの方が良いです．

2024-02-09 11:07 UTC, Geson-anko requested changes
@yuntan 実装ありがとうございます．とても参考になりました．MainThreadの実装はせず，WebApiHandlerクラスのみの実装にしていただけるとありがたいです．

2024-02-09 11:07 UTC, Geson-anko commented on ami/threads/main_thread.py
> +        return {"result": "ok", "status": "active"}
実処理追加
```suggestion
    def _post_resume(self) -> dict:
        # TODO: Resume training and inference threads
        self._logger.info("Resuming threads")
        self._controller.resume()
        return {"result": "ok", "status": "active"}
```

2024-02-09 11:07 UTC, Geson-anko commented on ami/threads/main_thread.py
> +        return {"result": "ok", "status": "paused"}
実処理追加
```suggestion
    def _post_pause(self) -> dict:
        # TODO: Pause training and inference threads
        self._logger.info("Pausing threads")
        self._controller.pause()
        return {"result": "ok", "status": "paused"}
```

2024-02-09 11:07 UTC, Geson-anko commented on ami/threads/main_thread.py
> +        return {"result": "ok", "status": "active"}
ここは要らないかと
```suggestion
```

2024-02-09 11:07 UTC, Geson-anko commented on ami/threads/main_thread.py
> +        pass
`Thread`クラス周りはリファクタリングするのですが，参考のためにこのまま残しておいてください．

2024-02-09 11:07 UTC, Geson-anko commented on samples/web_api_demo.py
`WebApiHandler`のみのデモに変えてもらえますか？

2024-02-09 11:40 UTC, Geson-anko commented on ami/threads/main_thread.py
> +    _handler: WebApiHandler
コンストラクタで定義する項目は記述しなくて良いです．
```suggestion
```

2024-02-10 11:36 UTC, yuntan commented
@Geson-anko レビューを反映しました。テストは試行錯誤中です。

テストが通るように `git rebase main` して `git push -f feature/#26/web-api-demo` した方が良いですか？（意味が分からなかったら聞いてください）

2024-02-10 13:20 UTC, Geson-anko reviewed
@yuntan 修正対応ありがとうございます．基本的に private にするのは素晴らしいですね．アクセスされることが想定されない変数が見やすくて良いです．
あとはテストコードがかければ十分かと．

2024-02-10 13:20 UTC, Geson-anko commented on ami/threads/web_api_handler.py
> +    """Web API handler class."""
docstringに issue #26 に書いた使い方を必要十分量で良いので記述してください．どのエンドポイントに`GET` / `POST` するとどうなるか，という内容です．記述した処理への参照だけでも構いません．

ちなみに日本語OKです．

2024-02-10 13:20 UTC, Geson-anko commented on ami/threads/main_thread.py
`web_api_demo.py`だけでhandlerの呼び出し方がわかるので，一旦 `main_thread.py`は削除でお願いします．

2024-02-10 13:24 UTC, Geson-anko commented
> @Geson-anko レビューを反映しました。テストは試行錯誤中です。
> 
> テストが通るように `git rebase main` して `git push -f feature/#26/web-api-demo` した方が良いですか？（意味が分からなかったら聞いてください）

@yuntan GitHub actionsのmypyのエラーメッセージ的には，問題箇所は別にありますね．`WebApiHandler`に型アノテーションをつけ忘れている箇所があるのと，おそらく`bottle`モジュールが型アノテーションしてないせいでエラー出てますね．`no-untyped-call`は設定で切らないといけないです．main ブランチに修正パッチ送るので mergeしてください．
```
ami/threads/web_api_handler.py:23: error: Function is missing a return type annotation  [no-untyped-def]
ami/threads/web_api_handler.py:23: note: Use "-> None" if function does not return a value
samples/web_api_demo.py:6: error: Call to untyped function "run" in typed context  [no-untyped-call]
ami/threads/main_thread.py:18: error: Call to untyped function "run" in typed context  [no-untyped-call]
```

2024-02-10 13:25 UTC, Geson-anko commented on ami/threads/web_api_handler.py
> +    def run(self):
型アノテーション忘れ
```suggestion
    def run(self) -> None:
```

2024-02-10 19:23 UTC, yuntan commented on ami/threads/main_thread.py
削除しました。

2024-02-10 19:24 UTC, yuntan commented
`no-untyped-call` の設定無しでもテストは通るので、一旦コミットを差し戻しました。

2024-02-11 01:49 UTC, yuntan commented
@Geson-anko docstringの追記とテストの追加を行いました。

2024-02-11 03:58 UTC, Geson-anko approved these changes
@yuntan 修正ありがとうございます。非推奨エイリアスが入っていたので若干の修正が必要ですが、それを終えたらマージしてください。

2024-02-11 03:58 UTC, Geson-anko commented on ami/threads/web_api_handler.py
> +        status: str = ""
宣言だけにすると変な値を混入させず、かつどんな変数が使われているのか分かりやすくなるので良いです。
```suggestion
        status: str
```

2024-02-11 03:58 UTC, Geson-anko commented on tests/threads/test_web_api_handler.py
> +from typing import Generator
`typing.Generator`は非推奨のエイリアスです。
```suggestion
from collections.abc import Generator
```
https://docs.python.org/ja/3/library/typing.html#typing.Generator

2024-02-11 07:46 UTC, merged