RandomDataBufferを実装
MLShukai/ami pull request #68
Opened 2024-02-21 15:42 UTC by myxyy

## 概要

https://github.com/MLShukai/ami/issues/60
コンストラクタで指定したKeyに対応する値を記録するよう一般化

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-02-22 03:26 UTC, Geson-anko approved these changes
@myxyy 実装ありがとうございます。クラスdocstringの記述をお願いします。
機能的には問題ありません。

2024-02-22 03:26 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +class RandomDataBuffer(BaseDataBuffer):
簡易で良いのでどのようにデータを保存するか、その方法に関してdocstringを記述してください。

2024-02-24 14:08 UTC, myxyy commented on ami/data/buffers/random_data_buffer.py
> +class RandomDataBuffer(BaseDataBuffer):
https://github.com/MLShukai/ami/pull/68/commits/2fddf8d01751713f1db11c4605b18a43427a82ff
docstring追記しました

2024-02-24 23:13 UTC, Geson-anko requested changes
@myxyy 修正ありがとうございます。コロナで体調が優れないようですので、まずは療養を優先してください。少し修正がありますが、私の作業環境が復帰したら直します。

2024-02-24 23:13 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +            key_list (list[DataKeys]): a list of keys to save whose values to buffer.
```suggestion
            max_len : max length of buffer.
            key_list : a list of keys to save whose values to buffer.
```
型記述はなくて良いです。型アノテーションによって示す事が可能となり、冗長となりました。

2024-02-24 23:13 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +            step_data (StepData): A single step of data.
```suggestion
            step_data : A single step of data.
```

2024-02-24 23:13 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +            new_data (RandomDataBuffer): A buffer to concatenate.
```suggestion
            new_data : A buffer to concatenate.
```

2024-02-24 23:13 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +                self.__buffer_dict[key].append(step_data[key])
```suggestion
                v = step_data[key]
                assert isinstance(v, Tensor), "Got data must be Tensor."
                self.__buffer_dict[key].append(v)
```
値がAny型なのでTensorかどうかをチェックする必要があります。`torch.stack`で結局エラーが出るからですね。ただmake datasetが呼ばれるのはしばらくランタイムが経過してからと想定されるので、今回の修正のような早期のエラー判定が必要になります。

2024-02-26 12:15 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +            key_list (list[DataKeys]): a list of keys to save whose values to buffer.
42127e9: docstringから冗長な型情報を削除

2024-02-26 12:15 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +            step_data (StepData): A single step of data.
42127e9: docstringから冗長な型情報を削除

2024-02-26 12:16 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +            new_data (RandomDataBuffer): A buffer to concatenate.
42127e9: docstringから冗長な型情報を削除

2024-02-26 12:18 UTC, Geson-anko commented on ami/data/buffers/random_data_buffer.py
> +                self.__buffer_dict[key].append(step_data[key])
`torch.tensor`によって任意のデータをテンソル型へ変換するようにしました。
0dec79b: Dataをappendする際にTensorに変換

2024-02-26 12:21 UTC, Geson-anko approved these changes
@myxyy 修正したので Approveします。

2024-02-27 02:30 UTC, merged