ImageVAETrainerの実装
MLShukai/ami pull request #75
Opened 2024-03-05 16:18 UTC by myxyy

## 概要

https://github.com/MLShukai/ami/issues/62
mypyが通らないのと
on_model_wrappers_dict_attachedでのencoder/decoderの取得が合ってるか自信がないので見ていただきたいです

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make run`コマンドでローカルでテストしましたか?

## 補足

2024-03-06 02:50 UTC, Geson-anko requested changes
@myxyy 実装ありがとうございました。このAMI Systemの独自フレームワークが存在するので、やはり一度ペアプロ的な感じで共有しないといけませんね。早急に勧めます。

これは今回のPRとは関係の無い気づきですが、Inference Threadでデータが集まっていない場合（0もしくはバッチサイズに満たない場合）、学習をスキップする必要が出てきます。`is_trainable() -> bool`メソッドを`BaseTrainer`に実装し、`TrainingThread`のループ上でチェックするのが良いと思いました。

### スケッチ
```py
class BaseTrainer:
    ...
    def is_trainable(self) -> bool:
        return True

class ImageVAETrainer(BaseTrainer):
    def is_trainable():
        return len(self.data_user.get_new_dataset()) > self.batch_size
```

2024-03-06 02:50 UTC, Geson-anko commented on ami/trainers/image_vae_trainer.py
> +        optimizer = self.partial_optimizer(self.vae.parameters())
```suggestion
        self.optimizer_state = self.partial_optimizer(self.vae.parameters()).state_dict()

    def train(self) -> None:
        self.vae = VAE(self.encoder.model, self.decoder.model)
        optimizer = self.partial_optimizer(self.vae.parameters())
```
これは`suggestion`では無いのですが、もしUnwrapされたモデルを用いて `VAE`をコンストラクトしたい場合は、学習時に毎回呼ばれる`train()`メソッド無いでモデルを構築してください。

2024-03-06 12:25 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +        self.decoder: Conv2dDecoder = self.get_training_model(ModelNames.IMAGE_DECODER).model
@Geson-anko 
`VAE`のコンストラクタ引数の型が`Encoder`と`Decoder`なんですがこれらは`ModelWrapper[Encoder]`と`ModelWrapper[Decoder]`にするべきでしょうか？

2024-03-06 12:29 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +        self.decoder: Conv2dDecoder = self.get_training_model(ModelNames.IMAGE_DECODER).model
@Geson-anko 
https://github.com/MLShukai/ami/pull/75#discussion_r1513739515
すみませんこっちで言及してましたね

2024-03-07 12:45 UTC, myxyy commented on ami/data/buffers/buffer_names.py
> +    IMAGE_BUFFER = "image_buffer"
https://github.com/MLShukai/ami/pull/75/commits/f895bb4db250dc450da0becd7f2bc1862baa1fa7
修正しました

2024-03-07 12:45 UTC, myxyy commented on tests/trainers/test_image_vae_trainer.py
> +            device = "cpu"
https://github.com/MLShukai/ami/pull/75/commits/f23a0c30561c7e31c775487b529dd79292b7eea4
fixtureにしました

2024-03-07 12:49 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +from ami.models.vae import VAE, Conv2dDecoder, Conv2dEncoder
https://github.com/MLShukai/ami/pull/75/commits/96a69bb4556226030b54237157d9eda9c708ec60
修正しました

2024-03-07 12:50 UTC, myxyy commented on tests/trainers/test_image_vae_trainer.py
> +                ModelNames.IMAGE_DECODER: ModelWrapper(image_decoder, device, True),
https://github.com/MLShukai/ami/pull/75/commits/14753b12abb78f1d1ba018639bd340e5356f0489
修正しました

2024-03-09 09:24 UTC, Geson-anko commented
@myxyy どうやら ここの型エイリアスを `ModelWrapper[Any]`にしないといけないようです。
`get_training_model`などのメソッドにオプショナル引数として型を指定可能にし、型チェックをする処理を記述すればGenericsでなんとかなるかもしれませんが、pythonにしては冗長なのと、結局`ModelWrapper[Any]`にするのとあんまり変わらないですし、多分下の例ではmypyに怒られるのでコストがかかりすぎるかと
https://github.com/MLShukai/ami/blob/feature/%2362/implement-image-vae-trainer/ami/trainers/base_trainer.py#L12

```py
T  = TypeVar("T")
class BaseTrainer:
   ...
   def get_training_model(self, name: str, type: T = object) -> ModelWrapper[T]:
       ...
```

2024-03-09 11:46 UTC, Geson-anko reviewed
先ほどコードを読んでいる時に気づいた修正箇所です。

2024-03-09 11:46 UTC, Geson-anko commented on ami/trainers/image_vae_trainer.py
> +        self.optimizer_state = self.partial_optimizer(self.vae.parameters()).state_dict()
以前の学習の状態を一時保存するのでこうですね。
```suggestion
        self.optimizer_state = optimizer.state_dict()
```

2024-03-09 11:46 UTC, Geson-anko commented on ami/trainers/image_vae_trainer.py
> +        self.data_user = self.get_data_user(BufferNames.IMAGE)
ここ`image_data_user`にしてください。
```suggestion
        self.image_data_user = self.get_data_user(BufferNames.IMAGE)
```

2024-03-09 13:42 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +        self.optimizer_state = self.partial_optimizer(self.vae.parameters()).state_dict()
https://github.com/MLShukai/ami/pull/75/commits/42736a45d0c297feafed76f0af4184892ae83040
修正しました

2024-03-09 13:42 UTC, myxyy commented
> @myxyy mypyが通らない件ですが、どうやら ここの型エイリアスを `ModelWrapper[Any]`にしないといけないようです。 https://github.com/MLShukai/ami/blob/feature/%2362/implement-image-vae-trainer/ami/trainers/base_trainer.py#L12
> 
> `get_training_model`などのメソッドにオプショナル引数として型を指定可能にし、型チェックをする処理を記述すればGenericsでなんとかなるかもしれませんが、pythonにしては冗長なのと、結局`ModelWrapper[Any]`にするのとあんまり変わらないですし、多分下の例ではmypyに怒られるのでコストがかかりすぎるかと
> 
> ```python
> T  = TypeVar("T")
> class BaseTrainer:
>    ...
>    def get_training_model(self, name: str, t: type[T] = object) -> ModelWrapper[T]:
>        ...
> ```

https://github.com/MLShukai/ami/pull/75/commits/9a805450879313139be32b535815fbdbdfe3f1fb
Anyに変えてmypyエラーが消えました

2024-03-09 13:43 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +        optimizer = self.partial_optimizer(self.vae.parameters())
https://github.com/MLShukai/ami/pull/75/commits/23c761b2631da98dfaabbf3a996f71a0466cf53c
optimizer_stateの取得含めて修正しました

2024-03-09 13:47 UTC, myxyy commented on ami/trainers/image_vae_trainer.py
> +        self.data_user = self.get_data_user(BufferNames.IMAGE)
https://github.com/MLShukai/ami/pull/75/commits/c668f16fa06ceae56ea13c08794381d4801e43e8
修正しました

2024-03-10 00:40 UTC, Geson-anko approved these changes
@myxyy コメント追加したり見やすくしたりしておきました。Approveしてマージしますね。
KL lossの計算は毎回sumとかmeanとかをどうするか迷うのですが、Primitive AMIの方に合わせました。
https://github.com/MLShukai/ami/pull/75/commits/0ad788192f5349bf0652036b10d48002614b52d3

2024-03-10 00:49 UTC, merged